Story/14836 remove global width constraints
torch-ai/public-website pull request #47
Opened 2022-06-27 18:29 UTC by gm3197

* Remove global p `max-width`
* Use Grid to fix overflowing as a result of ^

2022-06-28 19:56 UTC, michaeljwiebe commented on pages/impact/index.tsx
>                    <Grid container marginCenter id="public">
second id="public" on this one

2022-06-28 21:00 UTC, michaeljwiebe commented on pages/impact/index.tsx
> +                      <Grid size={{ Xs: 12, Lg: 3 }}>
to match the current site i think this should be 4 at least then Xl: 3 is ok

2022-06-28 21:00 UTC, michaeljwiebe commented on pages/impact/index.tsx
> +                      <Grid size={{ Xs: 12, Lg: 3 }}>
thats all the others below it too

2022-06-28 21:00 UTC, michaeljwiebe requested changes
see comments

2022-06-29 13:59 UTC, michaeljwiebe commented on pages/impact/index.tsx
> +                      <Grid size={{ Xs: 12, Lg: 3 }}>
did you change this? or is there a problem?

2022-07-01 20:20 UTC, gm3197 commented on pages/impact/index.tsx
> +                      <Grid size={{ Xs: 12, Lg: 3 }}>
it's _actually_ done this time

2022-07-01 20:38 UTC, michaeljwiebe approved these changes

2022-07-01 20:39 UTC, merged